 const i18Obj = {
    "RU": {
        "values" : "НАШИ ЦEННОСТИ",
        "about-us" : "О НАС",
        "career" : "КАРЬЕРА",
        "contact" : "СВЯЗАТЬСЯ С НАМИ",
        "main-suptitle": "Робототехника открывает технологический мир творчества, погружая разработчика в изобретательскую инженерно-конструкторскую деятельность. В мехатронике сплетаются воедино механика, электроника и программирование. В технологическом веке вся работа автоматизируется, позволяя менять жизнь человека к лучшему, продвигать вперед науку, расширяя человеческие возможности.",
        "values-title1" : "Ответственность и добросовестность",
        "values-suptitle1" : "Основная ценность нашей компании.",
        "values-title2" : "Ориентируемся на результат",
        "values-suptitle2" : "Мы стремимся действовать безотлагательно и выполнять свои обязательства. Мы совершенствуемся каждый день, чтобы создавать качественный продукт, соответствующий требованиям наших клиентов.",
        "values-title3" : "Инновационность",
        "values-suptitle3" : "Мы нацелены на создание и внедрение новых технологий и подходов. Мы любопытны, настойчивы и полны решимости преодолевать барьеры.",
        "values-title4" : "Командная работа",
        "values-suptitle4" : "Отношения в нашей команде построены на принципе уважения. Команда работает так, чтобы раскрывать потенциал  каждого сотрудника и совместными усилиями достигать наилучшего результата.",
        "values-title5" : "Профессиональные сотрудники",
        "values-suptitle5" : "В нашей команде работают квалифицированные, опытные и мотивированные люди.",
        "about-us-main-suptitle" : "Область нашей профессиональной деятельности включает проектирование, исследование, производство и эксплуатацию мехатронных и робототехнических систем для применения в автоматизированном производстве, сельском хозяйстве, на транспорте, в медицине и других областях.",
        "about-us-title1" : "СИСТЕМЫ ВИДЕООБРАБОТКИ",
        "about-us-suptitle1" : "Обработка данных телевизионных, тепловизионных систем видеонаблюдения.",
        "about-us-title2" : "ИСКУССТВЕННЫЙ ИНТЕЛЛЕКТ",
        "about-us-suptitle2" : "Использование искусственного интеллекта, машинного обучения в системах компьютерного зрения, анализа данных, автоматического управления и принятия решений.",
        "about-us-title3" : "АВТОМАТИЗИРО - ВАННЫЕ СИСТЕМЫ УПРАВЛЕНИЯ",
        "about-us-suptitle3" : "Повышение эффективности, быстрый сбор и обработка информации, повышенная точность, минимизация вмешательства человека в принятие решений.",
        "about-us-title4" : "РОБОТОТЕХНИКА",
        "about-us-suptitle4" : "Разработка программируемых механических устройств, способных выполнять задачи и взаимодействовать с внешней средой без помощи человека.",
        "tech-main-suptitle" : "В наших проектах мы стремимся применять новаторские подходы к разработке, использовать современную элементную базу и новые технологии для создания прогрессивной и конкурентоспособной продукции.",
        "tech-title1" : "РАЗРАБОТКА МЕХАНИКИ",
        "tech-suptitle1" : " Разработка конструктива изделий с проработкой компоновки и дизайна. Подбор материалов и унифицированных узлов происходит с учётом максимально широкого списка необходимых параметров и с учётом последующих логистических задач. Механические и кинематические расчёты производятся с использованием расширенного математического аппарата и передового специализированного ПО. Слаженная команда разработчиков распределяет задачи согласно сильным сторонам каждого участника.",
        "tech-title2" : "РАЗРАБОТКА ЭЛЕКТРОНИКИ",
        "tech-suptitle2" : "Проектирование и расчет электронных схем на основе обширной научно-технической базы с применением современных электронных компонентов и программных средств разработки. Cоздание печатных плат и программного обеспечения для их эффективной работы, конечная наладка готового устройства.",
        "tech-title3" : "РАЗРАБОТКА ПО",
        "tech-suptitle3" : "Разработка комплексного программного обеспечения, позволяющая наделить продукт автономностью и предоставляющая качественный уровень пользовательского взаимодействия с ним. Для осуществления этого у нас собрана междисциплинарная команда разработчиков, состоящая из специалистов машинного обучения, разработчиков программ для конечных пользователей и разработчиков программного обеспечения для встраиваемых систем.",
        "career-main-suptitle" : "Стань частью команды R&D Mecaro. Мы ищем единомышленников влюбленных в свою профессию, постоянно развивающихся, готовых создавать высококачественный продукт, стремящихся к новым вершинам. Присоединяйся к нам!",
        "contact-title1" : "СОТРУДНИЧЕСТВО",
        "contact-title2" : "СОИСКАТЕЛЯМ",
        "contact-title3" : "НАШ АДРЕС",
        "contact-address" : "220070 Республика Беларусь г. Минск, ул. Солтыса 187",
        "Responsibilities" : "Обязанности:",
        "must-haves" : "Требования:",
        "nice-to-haves" : "Будет преимуществом",
        "what me offer" : "Что мы предлагаем:",


        "vacancy1-title" : "Инженер-конструктор (оптика, приборостроение)",
        "v1r1" : "- Разработка эскизных, технических и рабочих проектов сложных и средней сложности электронно-оптических изделий (системы искусственного зрения, приборы наблюдения)",
        "v1r2" : "- Компоновка изделия и теоретические увязки отдельных элементов конструкций с учетом технологических особенностей производства, чертежей и паспортов покупных компонентов",
        "v1r3" : "- Создание 3D-моделей деталей, сборочных единиц",
        "v1r4" : "- Оформление комплекта КД и ЭД в соответствии с ЕСКД",
        "v1r5" : "- Конструкторское сопровождение производства и испытаний",
        "v1r6" : "- Проведение поисковых исследований и формирование отчета",
        "v1r7" : "- Анализ типовых конструкций и конструктивных решений",
        "v1r8" : "- Анализ и разработка технического задания",
        "v1r9" : "- Анализ технико-экономических показателей на проектируемые изделия",
        "v1r10" : "- Анализ лучших практик в области создания перспективных изделий",
        "v1r11" : "- Выполнение геометрических, прочностных расчетов и др",
        "v1r12" : "- Выполнение расчетов надежности компонентов",
        "v1m1" : "- Образование высшее (инженер-конструктор)",
        "v1m2" : "- Среда разработки – SolidWorks",
        "v1m3" : "- Опыт разработки фрезерованных корпусов (ал. сплавы) для приборов",
        "v1m4" : "- Знание конъюнктуры рынка камер(день/ночь), объективов фиксир. и моторизованных",
        "v1m5" : "- Чтение и составление оптических схем",
        "v1m6" : "- Умение работать в команде",
        "v1m7" : "- Опыт работы: 3-5 лет",



        "vacancy2-title" : "Инженер-конструктор (машиностроение)",
        "v2r1" : "- Разработка узлов или систем гусеничных машин",
        "v2r2" : "- Компоновка узлов, систем и теоретические увязки отдельных элементов конструкций с учетом окружающей обстановки, технологических особенностей производства, чертежей и паспортов покупных компонентов",
        "v2r3" : "- Проведение расчетов для обоснования выбора конструкторских решений и составных частей (кинематические, прочностные, расчет сварных швов, расчет на устойчивость и т.п.)",
        "v2r4" : "- Создание 3D-моделей деталей, сборочных единиц",
        "v2r5" : "- Оформление комплекта КД и ЭД в соответствии с ЕСКД",
        "v2r6" : "- Авторский надзор в производстве",
        "v2m1" : "- Образование высшее (инженер-конструктор, БНТУ)",
        "v2m2" : "- Среда разработки – SolidWorks",
        "v2m3" : "- Знание методов и принципов конструирования",
        "v2m4" : "- Опыт разработки и расчета пространственных силовых сварных конструкций",
        "v2m5" : "- Опыт разработки гидравлических систем (приветствуется)",
        "v2m6" : "- Опыт работы в области разработки или модернизации гусеничных транспортных средств (приветствуется)",
        "v2m7" : "- Опыт работы в автомобилестроении: 3-5 лет",



        "vacancy3-title" : "Инженер-схемотехник",
        "v3r1" : "- Разработка схемотехнических решений",
        "v3r2" : "- Моделирование (макетирование) разработанных схем",
        "v3r3" : "- Разработка топологии печатных плат",
        "v3r4" : "- Отладка и испытания разрабатываемого оборудования",
        "v3r5" : "- Разработка конструкторской и технологической документации",
        "v3r6" : "- Сопровождение на производстве разработанных изделий",
        "v3m1" : "- Опыт работы в области проектирования РЭА",
        "v3m2" : "- Знание современной компонентной базы",
        "v3m3" : "- Знание и опыт разработки устройств на основе микроконтроллеров",
        "v3m4" : "- Знание и опыт разработки аналоговой схемотехники",
        "v3m5" : "- Владение средой проектирования Altium Designer",
        "v3m6" : "- Опыт создания конструкторской документации",
        "v3m7" : "- Технический английский (чтение и понимание)",



        "vacancy4-title" : "Инженер-программист микроконтроллеров",
        "v4r1" : "- Разработка программного обеспечения для микроконтроллеров",
        "v4r2" : "- Отладка, оптимизация кода, пусконаладка",
        "v4r3" : "- Взаимодействие со схемотехники по вопросам схемотехнических решений",
        "v4r4" : "- Поддержка и доработка существующих разработок радиоэлектронной аппаратуры",
        "v4m1" : "- Знание и практический опыт применения С и С++",
        "v4m2" : "- Опыт работы с микроконтроллерами на ядрах Cortex M",
        "v4m3" : "- Желателен опыт работы с микроконтроллерами STM, Texas Instrument, Microchip.",
        "v4m4" : "- Приветствуется опыт разработки ПО c использованием RTOS",
        "v4m5" : "- Опыт программирования прикладного ПО в QT будет преимуществом",
        "v4m6" : "- Базовые знания в области электроники и схемотехники, понимание принципиальных электрических схем",
        "v4m7" : "- Умение быстро переключаться между проектами",
        "v4m8" : "- Уверенное пользование Git",



        "vacancy5-title" : "C++ Разработчик (Встраиваемые системы и работа с видео)",
        "v5r1" : "- Подключение и настройка камер для встраиваемых систем",
        "v5r2" : "- Исследование и выбор оптимального решения для передачи видео для встраиваемых систем",
        "v5r3" : "- Проектирование, написание и поддержка эффективного и надёжного кода на C++ ",
        "v5r4" : "- Организация кодовой базы и обеспечение качества кода",
        "v5m1" : "- Опыт разработки на C++ более трёх лет",
        "v5m2" : "- Знание современных стандартов C++",
        "v5m3" : "- Знание современных видео-кодеков: H.264, H.265, VP9",
        "v5m4" : "- Опыт работы с передачей видеопотока по сети",
        "v5m5" : "- Знание интерфейсов: USB, CSI, UART, CAN",
        "v5m6" : "- Опыт работы с Linux, знание основных команд bash",
        "v5m7" : "- Знание и понимание основных принципов ООП",
        "v5m8" : "- Знание и понимание принципов SOLID",
        "v5m9" : "- Опыт работы с системой контроля версий git",
        "v5m10" : "- Уровень английского - не ниже Intermediate",
        "v5n1" : "- Опыт работы с передачей видео в режиме реального времени",
        "v5n2" : "- Опыт работы с любой из встраиваемых платформ: Nvidia Jetson, Xilinx, NXP",
        "v5n3" : "- Опыт работы с библиотеками видео: gstreamer, ffmpeg, libav, libvlc",
        "v5n4" : "- Знание шаблонов проектирования ООП",
        "v5n5" : "- Знание и опыт работы с Qt",
        "v5n6" : "- Опыт работы с CUDA",
        "v5n7" : "- Опыт работы с тепловизионными камерами ",
        "v5n8" : "- Высшее образование по специальностям: информатика, математика, радиоэлектроника или физика",
        "v5w1" : "- Участие в разработке инновационных продуктов",
        "v5w2" : "- Сложные и интересные задачи, быстрый профессиональный рост",


        "vacancy6-title" : "Инженер-разработчик систем компьютерного зрения и машинного обучения",
        "v6r1" : "- Исследование в области новых алгоритмов машинного обучения",
        "v6r2" : "- Разработка алгоритмов компьютерного зрения для встраиваемых платформы",
        "v6r3" : "- Оптимизация существующих моделей под встраиваемые платформы",
        "v6r4" : "- Техническое руководство другими инженерами машинного обучения",
        "v6m1" : "- Более трёх лет опыта в разработке и реализации методов компьютерного зрения или исследования в смежных областях",
        "v6m2" : "- Знание языка программирования python: numpy, scipy",
        "v6m3" : "- Опыт работы с библиотеками машинного обучения: Pytorch, TensorFlow, OpenCV",
        "v6m4" : "- Опыт работы с Linux, знание основных команд bash",
        "v6m5" : "- Умение работать в команде",
        "v6m6" : "- Знание и понимание основных принципов ООП ",
        "v6m7" : "- Опыт работы с системой контроля версий git",
        "v6m8" : "- Уровень английского -- Intermediate",
        "v6n1" : "- Опыт работы с встраиваемыми платформами компьютерного зрения (Nvidia Jetson, Rasbery Pi, Intel NCS)",
        "v6n2" : "- Опыт работы с C++",
        "v6n3" : "- Опыт работы с CUDA и TensorRT",
        "v6n4" : "- Опыт работы с OpenVino",
        "v6w1" : "- Участие в разработке инновационных продуктов",
        "v6w2" : "- Участие в совершенствовании процессов машинного обучения в компании",
        "v6w3" : "- Сложные и интересные задачи, быстрый профессиональный рост",

    },
    "EN": {
        "values" : "OUR VALUES",
        "about-us" : "ABOUT US",
        "career" : "CAREERS",
        "contact" : "CONTACT US",
        "main-suptitle": "Robotics discovers the world of technological creativity, immerses the developer into inventive engineering activities. Mechatronics combines mechanics, electronics and programming. In the age of technologies all work is automated, that helps to change human lives for better, advance science and expand human abilities.",
        "values-title1" : "Responsibility and Conscientiousness ",
        "values-suptitle1" : "Are the main values of our company.",
        "values-title2" : "We are results-oriented",
        "values-suptitle2" : "We strive to act with urgency and fulfill our obligations. We improve constantly to create a high-quality product meeting the requirements of our customers. ",
        "values-title3" : "Innovations",
        "values-suptitle3" : "We are focused on creating and implementation of new technologies and approaches. We are curious, persistent and determined to overcome difficulties.",
        "values-title4" : "Team work",
        "values-suptitle4" : "Relations in our team are built on the principles of respect. It helps us to reveal the potential of each employee, and joint efforts give the best result.",
        "values-title5" : "We are the team of professionals",
        "values-suptitle5" : "There are qualified, experienced and motivated people work in our company.",
        "about-us-main-suptitle" : "The areas of our professional activities are: development, research, production and operation of mechatronic and robotic systems for implementation in automatic industrial production, agriculture, transport, medicine and other fields.",
        "about-us-title1" : "VIDEO - PROCESSING",
        "about-us-suptitle1" : "Data processing from television and thermal vision systems.",
        "about-us-title2" : "ARTIFICIAL INTELLIGENCE",
        "about-us-suptitle2" : "Artificial intelligence and machine learning application in computer vision systems, data analysis, automatic control and making decisions. ",
        "about-us-title3" : "AUTOMATIC CONTROL SYSTEMS",
        "about-us-suptitle3" : "Efficiency improvement, fast data collecting and processing, increased accuracy, minimizing human involvement in making decisions.",
        "about-us-title4" : "ROBOTICS",
        "about-us-suptitle4" : "Engineering of programmable mechanical devices which are capable of performing specific tasks and interact with external environment without human assistance.",
        "tech-main-suptitle" : "In our projects we strive to apply innovatory development approaches, to use modern element base and new technologies for creating progressive and competitive products.",
        "tech-title1" : "MECHANICAL ENGINEERING",
        "tech-suptitle1" : "Development of devices construction with layout and design engineering. Materials and unified units selection takes into account the widest list of necessary parameters and following logistical tasks. Mechanical and kinematical calculations are carried out with using of extended mathematical apparatus and improved specialized software. A well-coordinated team distributes tasks according to each participant strengths.",
        "tech-title2" : "ELECTRONICS ENGINEERING",
        "tech-suptitle2" : "Development and calculating of electronic circuits on the basis of extended scientific and technical knowledge with application of modern electronic components and computer-aided design tools. Creating of printed circuit boards and software for its efficient operation, final adjustment of the device.",
        "tech-title3" : "SOFTWARE ENGINEERING",
        "tech-suptitle3" : "Development of integrated software systems, that enables us to create a products with high automation and best user experience for our clients. To achieve this we have a cross-technology team of machine learning engineers, ui developer and embedded software engineers.",
        "career-main-suptitle" : "Become a part of R&D Mecaro team! We are looking for like-minded people who are in love with their profession, who are developing constantly and ready to create high-quality product, aspiring to new heights. Join us!",
        "contact-title1" : "COOPERATION ",
        "contact-title2" : "FOR APPLICANTS ",
        "contact-title3" : "OUR ADDRESS",
        "contact-address" : "187, Soltysa st., Republic of Belarus, 220070",
        "Responsibilities" : "Responsibilities:",
        "must-haves" : "Must-haves:",
        "nice-to-haves" : "Nice-to-haves:",
        "what me offer" : "What we offer:",


        "vacancy1-title" : "Инженер-конструктор (оптика, приборостроение)",
        "v1r1" : "- Разработка эскизных, технических и рабочих проектов сложных и средней сложности электронно-оптических изделий (системы искусственного зрения, приборы наблюдения)",
        "v1r2" : "- Компоновка изделия и теоретические увязки отдельных элементов конструкций с учетом технологических особенностей производства, чертежей и паспортов покупных компонентов",
        "v1r3" : "- Создание 3D-моделей деталей, сборочных единиц",
        "v1r4" : "- Оформление комплекта КД и ЭД в соответствии с ЕСКД",
        "v1r5" : "- Конструкторское сопровождение производства и испытаний",
        "v1r6" : "- Проведение поисковых исследований и формирование отчета",
        "v1r7" : "- Анализ типовых конструкций и конструктивных решений",
        "v1r8" : "- Анализ и разработка технического задания",
        "v1r9" : "- Анализ технико-экономических показателей на проектируемые изделия",
        "v1r10" : "- Анализ лучших практик в области создания перспективных изделий",
        "v1r11" : "- Выполнение геометрических, прочностных расчетов и др",
        "v1r12" : "- Выполнение расчетов надежности компонентов",
        "v1m1" : "- Образование высшее (инженер-конструктор)",
        "v1m2" : "- Среда разработки – SolidWorks",
        "v1m3" : "- Опыт разработки фрезерованных корпусов (ал. сплавы) для приборов",
        "v1m4" : "- Знание конъюнктуры рынка камер(день/ночь), объективов фиксир. и моторизованных",
        "v1m5" : "- Чтение и составление оптических схем",
        "v1m6" : "- Умение работать в команде",
        "v1m7" : "- Опыт работы: 3-5 лет",



        "vacancy2-title" : "Инженер-конструктор (машиностроение)",
        "v2r1" : "- Разработка узлов или систем гусеничных машин",
        "v2r2" : "- Компоновка узлов, систем и теоретические увязки отдельных элементов конструкций с учетом окружающей обстановки, технологических особенностей производства, чертежей и паспортов покупных компонентов.",
        "v2r3" : "- Проведение расчетов для обоснования выбора конструкторских решений и составных частей (кинематические, прочностные, расчет сварных швов, расчет на устойчивость и т.п.).",
        "v2r4" : "- Создание 3D-моделей деталей, сборочных единиц.",
        "v2r5" : "- Оформление комплекта КД и ЭД в соответствии с ЕСКД.",
        "v2r6" : "- Авторский надзор в производстве.",
        "v2m1" : "- Образование высшее (инженер-конструктор, БНТУ)",
        "v2m2" : "- Среда разработки – SolidWorks",
        "v2m3" : "- Знание методов и принципов конструирования",
        "v2m4" : "- Опыт разработки и расчета пространственных силовых сварных конструкций",
        "v2m5" : "- Опыт разработки гидравлических систем (приветствуется)",
        "v2m6" : "- Опыт работы в области разработки или модернизации гусеничных транспортных средств (приветствуется)",
        "v2m7" : "- Опыт работы в автомобилестроении: 3-5 лет",



        "vacancy3-title" : "Circuit engineer",
        "v3r1" : "- Engineering of electronic circuits",
        "v3r2" : "- Modeling (prototyping) of electronic circuits",
        "v3r3" : "- Development of printed circuit board layout",
        "v3r4" : "- Adjusting and testing of developed devices",
        "v3r5" : "- Development of design and technological documentation",
        "v3r6" : "- Maintenance on production",
        "v3m1" : "- Experience in development of electronic devices",
        "v3m2" : "- Knowledge of modern component base",
        "v3m3" : "- Experience in development of MCU-controlled devices",
        "v3m4" : "- Knowledge of analog circuitry",
        "v3m5" : "- Experience in Altium Designer CAD",
        "v3m6" : "- Experience in development of design documentation",
        "v3m7" : "- Technical English (reading and understanding)",



        "vacancy4-title" : "Embedded software engineer",
        "v4r1" : "- Microcontroller software development",
        "v4r2" : "- Debugging, code optimization, device adjustment",
        "v4r3" : "- Cooperating with circuit engineer in circuit development",
        "v4r4" : "- Device support and update",
        "v4m1" : "- Experience in C and C++",
        "v4m2" : "- Work experience with Cortex-M microcontrollers",
        "v4m3" : "- Work experience with STM, Texas Instruments, Microchip microcontrollers (nice-to-have)",
        "v4m4" : "- Experience in software development with using RTOS (nice-to-have)",
        "v4m5" : "- Experience in software development in QT (nice-to-have)",
        "v4m6" : "- Ability to work with multiple projects",
        "v4m7" : "- Basic knowledge in electronics, understanding of electronic circuits",
        "v4m8" : "- Experience with Git version control",



        "vacancy5-title" : "C++ Developer (Embedded Vision and Video Distribution)",
        "v5r1" : "- Connecting and configuring cameras to the embedded platform",
        "v5r2" : "- Research and select optimal video distribution solution for the embedded platform",
        "v5r3" : "- Designing, building, maintaining efficient and reliable C++ code",
        "v5r4" : "- Organizing code and assuring code quality",
        "v5m1" : "- Experience in C++ more than 3+ years",
        "v5m2" : "- Knowledge of modern C++ standards",
        "v5m3" : "- Knowledge of modern video codes (H.264, H.265, VP9)",
        "v5m4" : "- Experience with video streaming",
        "v5m5" : "- Knowledge of interfaces: USB, CSI, UART, CAN",
        "v5m6" : "- Experience with Linux, knowledge of bash command line",
        "v5m7" : "- Knowledge and understanding OOP principles",
        "v5m8" : "- Knowledge and understanding of SOLID principles",
        "v5m9" : "- Experience with git version control",
        "v5m10" : "- Level of English - Intermediate",
        "v5n1" : "- Experience with realtime video streaming",
        "v5n2" : "- Experience with any embedded platform (Nvidia Jetson, Xilinx, NXP)",
        "v5n3" : "- Experience with any video library (gstreamer, ffmpeg, libav, libvlc)",
        "v5n4" : "- Knowledge of OOP patterns",
        "v5n5" : "- Knowledge and experience with Qt",
        "v5n6" : "- Experience with CUDA",
        "v5n7" : "- Experience of working with thermal cameras",
        "v5n8" : "- Completed education in the field of computer science, software engineering, electrical engineering, physics",
        "v5w1" : "- Participating in development of cutting edge product",
        "v5w2" : "- Challenging tasks and fast professional growth",



        "vacancy6-title" : "Computer Vision and Machine Learning engineer",
        "v6r1" : "- Research of new machine learning algorithms",
        "v6r2" : "- Implementation and development of computer vision algorithms for embedded platforms",
        "v6r3" : "- Optimization of existing models for embedded platforms",
        "v6r4" : "- Technical guidance of other computer vision engineers",
        "v6m1" : "- 3+ years of professional experience in the development and implementation of computer vision methods or as a research assistant in relevant subject areas",
        "v6m2" : "- Knowledge of Python programming language and libraries (numpy, scipy)",
        "v6m3" : "- Experience with ML frameworks (Pytorch, TensorFlow, OpenCV)",
        "v6m4" : "- Experience with Linux, knowledge of bash command line",
        "v6m5" : "- Ability to work in a team and solution-oriented, innovative as well as independent way of working",
        "v6m6" : "- Knowledge and understanding OOP principles",
        "v6m7" : "- Experience with git version control",
        "v6m8" : "- Level of English - Intermediate",
        "v6n1" : "- Experience of working with Embedded ML platforms (Nvidia Jetson,Rasbery Pi, Intel NCS)",
        "v6n2" : "- Experience with C++",
        "v6n3" : "- Experience with CUDA and TensorRT",
        "v6n4" : "- Experience with OpenVino",
        "v6w1" : "- Participating in development of cutting edge product",
        "v6w2" : "- Participation in establishing better processes for ML in company",
        "v6w3" : "- Challenging tasks and fast professional growth",

    }
}
 export default i18Obj